daily

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,6 +6,58 @@
 # TravisCI Bash functions
 # https://github.com/travis-ci/travis-build/tree/master/lib/travis/build/bash
 
+_shared_script_check_author: &script_check_author |
+  Check_author()
+  {
+    local author="$1"
+    local github_api_url="https://api.github.com/search/users"
+    echo "Checking ${author} ..."
+    test "${author%@users.noreply.github.com}" == "${author}" || return 0
+    curl -s -G --data-urlencode "q=type:user in:email ${author}" "${github_api_url}" \
+      | grep -F -x '  "total_count": 1,'
+  }
+  test -z "${TRAVIS_COMMIT_RANGE}" \
+    || git show --no-patch --pretty="format:%ae" "${TRAVIS_COMMIT_RANGE}" \
+    | sort -u \
+    | while read -r author; do Check_author "${author}"; done
+
+_shared_script_check_executable: &script_check_executable |
+  # Scripts should be executable, all other files should not be executable
+  test -z "$(find bin/ -type f -name "*.sh" -not -executable)"
+  test -z "$(find . -type f -not -path "./.git/*" -not -path "./bin/*.sh" -executable)"
+
+_shared_script_install_phive: &script_install_phive |
+  # Install PHIVE (cached)
+  if [ ! -r "${HOME}/.phive/phive.phar" ]; then
+    mkdir -p "${HOME}/bin" "${HOME}/.phive"
+    if [ "$(phpenv version-name)" == 7.1 ]; then
+      # PHIVE v0.13.3 last version supporting PHP 7.1
+      travis_retry wget -O "${HOME}/.phive/phive.phar" \
+        "https://github.com/phar-io/phive/releases/download/0.13.3/phive-0.13.3.phar"
+      travis_retry wget -O "${HOME}/.phive/phive.phar.asc" \
+        "https://github.com/phar-io/phive/releases/download/0.13.3/phive-0.13.3.phar.asc"
+    else
+      travis_retry wget -O "${HOME}/.phive/phive.phar" "https://phar.io/releases/phive.phar"
+      travis_retry wget -O "${HOME}/.phive/phive.phar.asc" "https://phar.io/releases/phive.phar.asc"
+    fi
+    travis_retry gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=30 \
+      --recv-keys 0x9D8A98B29B2D5D79
+    if ! gpg --batch --verify "${HOME}/.phive/phive.phar.asc" "${HOME}/.phive/phive.phar"; then
+      echo "Invalid phive signature" 1>&2
+      rm -f "${HOME}/.phive/phive.phar"
+      exit 11
+    fi
+    rm "${HOME}/.phive/phive.phar.asc"
+  fi
+  install --verbose --mode=0755 --no-target-directory -D "${HOME}/.phive/phive.phar" "${HOME}/bin/phive"
+  export PATH="${HOME}/bin:${PATH}"
+
+# On CI-s without "travis_retry"
+# gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=30 --recv-keys 0x9D8A98B29B2D5D79 \
+#   || gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=30 --recv-keys 0x9D8A98B29B2D5D79
+
+if: "branch = master"
+
 language: "php"
 os:
   - "linux"
@@ -15,44 +67,6 @@ stages:
   - "commits"
   - "test"
 
-cache:
-  directories:
-    - "${HOME}/.phive"
-    - "${HOME}/.composer/cache"
-
-before_install:
-  - "phpenv config-rm xdebug.ini"
-  - |
-    # Download phive if not cached
-    if [ ! -r "${HOME}/.phive/phive.phar" ]; then
-      mkdir -p "${HOME}/bin" "${HOME}/.phive"
-      if [ "$(phpenv version-name)" == 7.1 ]; then
-        # phive v0.13.3 last version supporting PHP 7.1
-        travis_retry wget -O "${HOME}/.phive/phive.phar" "https://github.com/phar-io/phive/releases/download/0.13.3/phive-0.13.3.phar"
-        travis_retry wget -O "${HOME}/.phive/phive.phar.asc" "https://github.com/phar-io/phive/releases/download/0.13.3/phive-0.13.3.phar.asc"
-      else
-        travis_retry wget -O "${HOME}/.phive/phive.phar" "https://phar.io/releases/phive.phar"
-        travis_retry wget -O "${HOME}/.phive/phive.phar.asc" "https://phar.io/releases/phive.phar.asc"
-      fi
-      travis_retry gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=30 --recv-keys 0x9D8A98B29B2D5D79
-      if ! gpg --batch --verify "${HOME}/.phive/phive.phar.asc" "${HOME}/.phive/phive.phar"; then
-        echo "Invalid phive signature" 1>&2
-        rm -f "${HOME}/.phive/phive.phar"
-        exit 11
-      fi
-      rm "${HOME}/.phive/phive.phar.asc"
-    fi
-  - 'install --verbose --mode=0755 --no-target-directory -D "${HOME}/.phive/phive.phar" "${HOME}/bin/phive"'
-  - 'travis_retry "${HOME}/bin/phive" install --force-accept-unsigned --trust-gpg-keys TRUSTED-KEY1,TRUSTED-KEY2'
-  - 'export PATH="${HOME}/bin:${PATH}"'
-  # Use Composer v1
-  - "composer self-update --1"
-  - "composer validate --strict"
-
-# On CI-s without "travis_retry"
-#   gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=30 --recv-keys 0x9D8A98B29B2D5D79 \
-#     || gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=30 --recv-keys 0x9D8A98B29B2D5D79
-
 jobs:
   include:
     - stage: "commits"
@@ -60,29 +74,26 @@ jobs:
       before_install: "skip"
       install: "skip"
       before_script: "skip"
-      script:
-        - |
-          Check_author()
-          {
-            local author="$1"
-            local github_api_url="https://api.github.com/search/users"
-            echo "Checking ${author} ..."
-            curl -s -G --data-urlencode "q=type:user in:email ${author}" "${github_api_url}" \
-              | grep -F -x '  "total_count": 1,'
-          }
-          git show --no-patch --pretty="format:%ae" "${TRAVIS_COMMIT_RANGE}" \
-            | sort -u \
-            | while read -r author; do Check_author "${author}"; done
+      script: *script_check_author
       after_script: "skip"
 
     - stage: "commits"
-      name: "Check file execution bits"
+      name: "Check file permissions"
       before_install: "skip"
       install: "skip"
       before_script: "skip"
-      script:
-        # Scripts should be executable, all other files should not be executable
-        - |
-          test -z "$(find bin/ -type f -name "*.sh" -not -executable)"
-          test -z "$(find . -type f -not -path "./.git/*" -not -path "./bin/*.sh" -executable)"
+      script: *script_check_executable
       after_script: "skip"
+
+cache:
+  directories:
+    - "${HOME}/.phive"
+    - "${HOME}/.composer/cache"
+
+before_install:
+  - "phpenv config-rm xdebug.ini"
+  - *script_install_phive
+  - 'travis_retry "${HOME}/bin/phive" install --force-accept-unsigned --trust-gpg-keys TRUSTED-KEY1,TRUSTED-KEY2'
+  # Use Composer v1
+  - "composer self-update --1"
+  - "composer validate --strict"
