today

diff --git a/monitoring/monit/services/ntpdate_script b/monitoring/monit/services/ntpdate_script
--- a/monitoring/monit/services/ntpdate_script
+++ b/monitoring/monit/services/ntpdate_script
@@ -13,11 +13,14 @@
 
 export NTPSERVERS="0.europe.pool.ntp.org"
 
+set -e
+
 Error() {
     local RET="$1"
 
     shift
-    echo -e "ERROR: $*" 1>&2
+    echo "ERROR: $*" 1>&2
+
     exit "$RET"
 }
 
@@ -25,14 +28,14 @@ OFFSET="$(/usr/sbin/ntpdate-debian -q \
     | sed -n -e '0,/^.*: \(adjust\|step\) time server [0-9a-f.:]\+ offset \(-\?[0-9.]\+\) sec$/s//\2/p')"
 
 if [ -z "$OFFSET" ]; then
-    Die 1 "Failed to measure offset"
+    Error 1 "Failed to measure offset"
 fi
 
 # Absolute milisecond offset
-OFFSET_MSEC="$(echo "( ${OFFSET#-} * 1000 )/1" | bc -q)"
+declare -i OFFSET_MSEC="$(echo "( ${OFFSET#-} * 1000 )/1" | bc -q)"
 
 if [ "$OFFSET_MSEC" -gt 128 ]; then
-    Die 2 "Measured offset is greater than +-128 ms."
+    Error 2 "Measured offset is greater than +-128 ms."
 fi
 
 exit 0
diff --git a/tools/hosthost b/tools/hosthost
--- a/tools/hosthost
+++ b/tools/hosthost
@@ -27,7 +27,7 @@ Error() {
     local RET="$1"
 
     shift
-    echo -e "ERROR ${RET}: $*" 1>&2
+    echo -e "ERROR: $*" 1>&2
 
     exit "$RET"
 }
