Add debian-setup plans, mainly TODO-s

diff --git a/tools/reboot b/tools/reboot
--- a/tools/reboot
+++ b/tools/reboot
@@ -2,7 +2,7 @@
 #
 # Safe reboot.
 #
-# VERSION       :0.1.1
+# VERSION       :0.1.2
 # DATE          :2016-02-08
 # AUTHOR        :Viktor Szépe <viktor@szepe.net>
 # URL           :https://github.com/szepeviktor/debian-server-tools
@@ -11,7 +11,7 @@
 # DEPENDS       :apt-get install grub-pc
 # LOCATION      :/usr/local/sbin/reboot
 
-# Usage/Remarks
+# Usage
 #
 #     REBOOT=1 reboot
 
@@ -19,7 +19,7 @@ GRUB_CONFIG="/boot/grub/grub.cfg"
 
 if [ "$REBOOT" != 1 ]; then
     echo "Try  REBOOT=1 reboot $*"
-    exit 0
+    exit 100
 fi
 
 # shellcheck disable=SC2016
@@ -27,7 +27,7 @@ FIRST_ROOT="$(sed -ne '/^menuentry/,${s/^\s*linux\b.*root=\(\S\+\).*$/\1/p;/^}/q
 DISK=""
 
 # Block device
-if [ "${FIRST_ROOT:0:4}" == "/dev" ]; then
+if [ "${FIRST_ROOT:0:5}" == "/dev/" ]; then
     DISK="$(realpath "$FIRST_ROOT")"
 fi
 
@@ -36,11 +36,13 @@ if [ "${FIRST_ROOT:0:5}" == "UUID=" ]; then
     DISK="$(readlink -e "/dev/disk/by-uuid/${FIRST_ROOT#UUID=}")"
 fi
 
-if [ -b "$DISK" ] && grep -q "^${DISK}\s" /proc/mounts; then
-    clear
-    /sbin/reboot "$@" &
-    tail -f /var/log/syslog
-else
-    echo "root not found (${FIRST_ROOT})" 1>&2
+# Not a mounted block device
+if ! [ -b "$DISK" ] || ! grep -q "^${DISK}\s" /proc/mounts; then
+    echo "Root device not found (${FIRST_ROOT})" 1>&2
     exit 1
 fi
+
+clear
+/sbin/reboot "$@" &
+# Follow syslog until actual reboot
+tail -f /var/log/syslog
