daily

diff --git a/debian-setup/_package-php-composer b/debian-setup/_package-php-composer
--- a/debian-setup/_package-php-composer
+++ b/debian-setup/_package-php-composer
@@ -2,13 +2,16 @@
 
 set -e -x
 
-# Current hash: https://composer.github.io/pubkeys.html
-COMPOSER_HASH=e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae
+# https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
+EXPECTED_SIGNATURE="$(wget -qO- "https://composer.github.io/installer.sig")"
+php -r 'copy("https://getcomposer.org/installer", "composer-setup.php");'
+ACTUAL_SIGNATURE="$(php -r 'echo hash_file("SHA384", "composer-setup.php");')"
 
-# Get Composer installer
-php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');
-if (hash_file('SHA384', 'composer-setup.php') === '${COMPOSER_HASH}') { echo 'Installer verified'; }
-else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
+if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
+    echo "ERROR: Invalid composer installer signature" 1>&2
+    rm -f composer-setup.php
+    exit 1
+fi
 
-php composer-setup.php --install-dir=/usr/local/bin --filename=composer
+php composer-setup.php --quiet
 rm -f composer-setup.php
